version: '3'

services:
  db:
    build: ./pg
    image: llng_pg
    environment:
      POSTGRES_USER: lemonldap
      POSTGRES_PASSWORD: lemonldap
      POSTGRES_DB: lemonldap
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  llng:
    build: ./llng
    image: llng
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
volumes: 
  postgresql:
