services:
  db:
    build: ./pg
    environment:
      POSTGRES_USER: lemonldap
      POSTGRES_PASSWORD: lemonldap
      POSTGRES_DB: lemonldap
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 30s
      retries: 5

  llng:
    build: ./llng
    ports:
      - "80:80"
    restart: always
    depends_on:
      db:
        condition: service_healthy
volumes: 
  postgresql:
