- name: "[MAIN] Remove Docker Compose files"
  ansible.builtin.file:
    state: absent
    path: "~/lemonldap/"

- name: "[MAIN] Copy Docker Compose files"
  ansible.builtin.copy:
    dest: "~/lemonldap/"
    src: "../files/"
  
- ansible.builtin.template:
       src: "../templates/docker-compose.yml.j2"
       dest: "~/lemonldap/docker-compose.yml"

- name: "[MAIN] up compose"
  community.docker.docker_compose_v2:
    project_src: "~/lemonldap/"
    remove_orphans: yes