CREATE TABLE USER(
  IdUser VARCHAR(255) PRIMARY KEY
);

CREATE TABLE TITLE(
    IdTitre VARCHAR(255) PRIMARY KEY,
    IdUser VARCHAR(255),
    Titres INTEGER,
    FOREIGN KEY (IdUser) REFERENCES USER(IdUser)
);

CREATE TABLE FRIENDS (
  IdUser VARCHAR(255),
  FriendId VARCHAR(255),
  PRIMARY KEY (IdUser, FriendId),
  FOREIGN KEY (IdUser) REFERENCES USER(IdUser) ON DELETE CASCADE,
  FOREIGN KEY (FriendId) REFERENCES USER(IdUser) ON DELETE CASCADE
);

CREATE TABLE COMPANY(
  IdCompany VARCHAR(255) PRIMARY KEY,
  Name VARCHAR(255)
);

CREATE TABLE AGENT(
    IdUser VARCHAR(255) PRIMARY KEY, 
    IdCompany VARCHAR(255),
    FOREIGN KEY (IdUser) REFERENCES USER(IdUser),
    FOREIGN KEY (IdCompany) REFERENCES COMPANY(IdCompany)
);

CREATE TABLE ROLE(
    IdRole VARCHAR(255) PRIMARY KEY,
    Name VARCHAR(255)
);

CREATE TABLE PERMISSION(
    IdPermission VARCHAR(255) PRIMARY KEY,
    Name VARCHAR(255)
);

CREATE TABLE ROLE_PERMISSION(
  IdRole VARCHAR(255),
  IdPermission VARCHAR(255),
  PRIMARY KEY (IdRole, IdPermission),
  FOREIGN KEY (IdRole) REFERENCES ROLE(IdRole) ON DELETE CASCADE,
  FOREIGN KEY (IdPermission) REFERENCES PERMISSION(IdPermission) ON DELETE CASCADE
);

CREATE TABLE TRAJET(
  IdTrajet VARCHAR(255) PRIMARY KEY
);

CREATE TABLE LUGGAGE(
  IdLuggage VARCHAR(255) PRIMARY KEY,
  IdUser VARCHAR(255),
  IdTrajet VARCHAR(255),
  Photo LONGBLOB,
  FOREIGN KEY (IdUser) REFERENCES USER(IdUser),
  FOREIGN KEY (IdTrajet) REFERENCES TRAJET(IdTrajet)
);