- name: "[MAIN] Stop & Remove Images/Volumes"
  community.docker.docker_compose_v2:
    project_src: "~/hexatransit-db/"
    state: absent
    remove_images: local
    remove_volumes: yes

- name: "[MAIN] Remove Docker Compose files"
  ansible.builtin.file:
    state: absent
    path: "~/hexatransit-db/"

- name: "[MAIN] Copy Docker Compose files"
  ansible.builtin.copy:
    dest: "~/hexatransit-db/"
    src: "../files/"

- name: "[MAIN] up compose"
  community.docker.docker_compose_v2:
    project_src: "~/hexatransit-db/"
    remove_orphans: yes