FROM coudot/lemonldap-ng:2.20.1

EXPOSE 80

COPY config/* /var/lib/lemonldap-ng/conf
COPY lemonldap-ng.ini /etc/lemonldap-ng

ARG LLNG_MANAGER
ARG LLNG_PORTAL
ARG LLNG_SSODOMAIN
RUN sed -i -e "s/manager\.example\.com/${LLNG_MANAGER}/g" \
    /etc/lemonldap-ng/* /var/lib/lemonldap-ng/conf/lmConf-* \
    && sed -i -e "s/auth\.example\.com/${LLNG_PORTAL}/g" \
    /etc/lemonldap-ng/* /var/lib/lemonldap-ng/conf/lmConf-* \
    && sed -i -e "s/example\.com/${LLNG_SSODOMAIN}  /g" \
    /etc/lemonldap-ng/* /var/lib/lemonldap-ng/conf/lmConf-*